package main.kotlin

object TokenType {
    const val ENTRY = "ENTRY"
    const val GO = "GO"
    const val EXTERN = "EXTERN"
    const val NAME = "NAME"
    const val NUMBER = "NUMBER"
    const val STRING = "STRING"
    const val UNARY_MINUS = "UNARY_MINUS"
    const val SINGLE_QUOTE = "SINGLE_QUOTE"
    const val LITERAL = "LITERAL"
    const val CHAR = "CHAR"
    const val LPAREN = "LPAREN"
    const val RPAREN = "RPAREN"
    const val COMMA = "COMMA"
    const val EQUAL = "EQUAL"
    const val SEMICOLON = "SEMICOLON"
    const val S_VAR = "S_VAR"
    const val T_VAR = "T_VAR"
    const val E_VAR = "E_VAR"
    const val ANGLE_L = "ANGLE_L"
    const val ANGLE_R = "ANGLE_R"
    const val LBRACE = "LBRACE"
    const val RBRACE = "RBRACE"
    const val COMMENT = "COMMENT"
    const val WHITESPACE = "WHITESPACE"
    const val UNKNOWN = "UNKNOWN"
    const val DIRECTIVE = "DIRECTIVE"
    const val STAR_LINE = "STAR_LINE"
    const val COLON = "COLON"
}
